### ISSUE TITLE
Error for Custom Filter List

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdGuardMiniForMac#340]
I get an error when trying to use this specific filter list: `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt`.

Does this error reproduce for you? Can anyone see why this will not upload?

**Comment by Oleg-Chashko** [comment]
**yokoffing**
Yes. I confirm the error.

**Error occurred:**
Unfortunately, your custom filter cannot be added due to an unexpected error.
<img width="1021" alt="Bildschirmfoto 2020-04-05 um 01 56 58" src="https://user-images.githubusercontent.com/62497891/78463742-d403eb80-76e0-11ea-9878-234ebd0443fb.png">
